### ISSUE TITLE
Make a lighter color for the interviewer text

### ISSUE THREAD

**Issue by jbhoskins** [jbhoskins/rmtpTagger#12]

**Comment by magpie2295** [comment]
I can do this with text.config(fg = 'some color') for every 4th line but I'll do that once you have FramedText working again

**Comment by jbhoskins** [comment]
Using the "tag" functionality of Text, we could maybe "tag" each line according to who is speaking, and then assign a background color to the tag - that might be interesting, because then we could also apply the <sp> tags on export using these same tags.

There's stuff on tags here - they're super useful, especially for what we are doing they have a lot of utility. I used them a lot in the re-implementation of FramedText
http://effbot.org/tkinterbook/text.htm

**Comment by magpie2295** [comment]
This is a more complex version of what I've done with dimming the interviewer text; I tagged all those paragraphs as 'interviewer'.  If we could grab those, you're right, we could just use those for export.
