### ISSUE TITLE
Confirm the format of the input interview as it is loaded

### ISSUE THREAD

**Issue by jbhoskins** [jbhoskins/rmtpTagger#28]
The algorithm we have for skipping interview text relies on the fact that the interview is set up as following:

```
Interviewer
\n
Interviewee
\n
```

etc. etc...

Where everything the person says is on one long line. If this format was broken, the tagging would not work.

**Comment by magpie2295** [comment]
I will write a readme for this specifically. I think I already have it.

**Comment by jbhoskins** [comment]
We could probably write a short validation script for this as well.
